# Generated by Django 5.0.7 on 2024-08-06 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_article_text_alter_article_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000, verbose_name='комментарий')),
                ('author', models.CharField(max_length=1000, verbose_name='автор')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='дата добавления')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='comment',
            field=models.ManyToManyField(to='main.comment'),
        ),
    ]
