# Generated by Django 5.0.7 on 2024-08-06 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_comment_article_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'комментарий', 'verbose_name_plural': 'комментарии'},
        ),
        migrations.AlterField(
            model_name='article',
            name='comment',
            field=models.ManyToManyField(to='main.comment', verbose_name='комментарии'),
        ),
    ]
