# Generated by Django 5.0.7 on 2024-08-06 17:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_comment_options_alter_article_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.CharField(max_length=1000, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='комментарий'),
        ),
    ]
