# Generated by Django 5.0.7 on 2024-08-09 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_comment_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='comment',
            field=models.ManyToManyField(null=True, to='main.comment', verbose_name='комментарии'),
        ),
    ]
