# Generated by Django 5.0.7 on 2024-08-09 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_article_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='comment',
            field=models.ManyToManyField(to='main.comment', verbose_name='комментарии'),
        ),
    ]
