# Generated by Django 5.0.7 on 2024-08-09 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_article_comment_comment_article_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='article',
        ),
        migrations.AddField(
            model_name='article',
            name='comment',
            field=models.ManyToManyField(to='main.comment', verbose_name='комментарии'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.CharField(max_length=1000, verbose_name='автор'),
        ),
    ]
