# Generated by Django 5.0.7 on 2024-09-10 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_article_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(default=1, upload_to='photos', verbose_name='изображение'),
            preserve_default=False,
        ),
    ]
